### ISSUE TITLE
Execution stopped error

### ISSUE THREAD

**Issue by nick-webster** [skygenomics/CSBB-v1.0#1]
Hi, I was trying CSBB on my Mac today. When I tried running any module using the Sample_File I get the following error:
Running R in Background (please be patient).....

Excecution Stopped because of errors ... Please See Possible Errors Section of README or Contact CSBB for bugs and issues

perl version is 5.18.2
R is 2.5.0  GUI 1.19
pandoc and python 3.5.2 are installed

Any ideas?

**Comment by nick-webster** [comment]
An update on the error using the Sample_File.txt:

I updated R to the latest 3.3.1 and tried again.  Here is the error:

Running R in Background (please be patient).....
Error in file(file, "rt") : cannot open the connection
Calls: as.matrix -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'Sample_File.txt ': No such file or directory
Execution halted

Excecution Stopped because of errors ... Please See Possible Errors Section of README or Contact CSBB for bugs and issues

I dragged and dropped the file to insert the path as directed

Nick

**Comment by csbbcompbio** [comment]
Hi Nick,
Hope you are doing fine. when you dragged the file from finder window in Mac there is space that comes at the end. Can you try removing the space and run again. It will definitely run.
Sorry the slow response. I was out of town.

Thanks,

Cheers !!

SkyGenomics

**Comment by nick-webster** [comment]
Hi,  that did the trick.  Thanks for the info on the extra space.

Nick

---

Nicholas Webster, Ph.D., M.A.
Professor of Medicine
Chief, Division of Endocrinology and Metabolism
Associate Director for Shared Resources, Moores Cancer Center
University of California, San Diego
9500 Gilman Drive
La Jolla CA 92093

On Jul 11, 2016, at 10:06 AM, Sky Genomics <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Nick,
Hope you are doing fine. when you dragged the file from finder window in Mac there is space that comes at the end. Can you try removing the space and run again. It will definitely run.
Sorry the slow response. I was out of town.

Thanks,

Cheers !!

SkyGenomics

**Comment by csbbcompbio** [comment]
Hi Nick,
Awesome that CSBB is working now. Hope you like the tool and do suggest us with any ideas you have and which you want as a module in CSBB. 

Thanks,

Cheers !!

Praneet Chaturvedi
Analyst Bioinformatics
CCHMC, Cincinnati, OH
